### ISSUE TITLE
Are GATT services and characteristics implemented?

### ISSUE THREAD

**Issue by enochc** [laptou/bluez-rs#22]
Once connected how do I interface with the GATT services and characteristics that are supported by the peripheral?

**Comment by enochc** [comment]
If not GATT, how can I just send some raw data that the Peripheral can receive and process properly?

**Comment by laptou** [comment]
To answer your question, no, this is not implemented.

Interacting with devices directly is not really part of BlueZ's management API, which is the only one that is currently implemented. In order to do what you're trying to do, you either need to open an L2CAP socket and communicate with the device through it, or use BlueZ's D-Bus API.

Someone has implemented this whole L2CAP business in C [here](https://github.com/evanslai/bluez-gatt/), and it seems like [these lines](https://github.com/evanslai/bluez-gatt/blob/46748d6b5b573f1c30ad54fcb0792510fa4c646a/btgatt-server.c#L651-L664) are a good place to start if you want to rewrite it in Rust. [This website](http://people.csail.mit.edu/albert/bluez-intro/x559.html) should also be helpful in figuring out how exactly to use these sockets, and [this is the kernel header](https://elixir.bootlin.com/linux/latest/source/include/net/bluetooth/l2cap.h#L65) where the options structures are defined.

If you'd like to take a stab at implementing it, let me know. Otherwise, I'll have to have a look at this sometime in January.

**Comment by enochc** [comment]
Thank you so much for your detailed response, I'm still learning a lot about bluetooth. It would be great to have a working GATT implementation but for my short term goals all I really need is a socket connection where I can send and receive raw bytes. Does Bluez not provide a socket? I need a "This is how bluetooth works and how you can interface with it" guide for developers, but apparently such a thing either doesn't exist or is very hard to find (not to mention os and hardware specific).

**Comment by laptou** [comment]
Yeah, Bluetooth is tricky. You communicate with devices using an RFCOMM or L2CAP socket (more information about this in the [Bluetooth Core specification](https://www.bluetooth.com/specifications/bluetooth-core-specification/), Vol. 3, Part A), which you can open [like so](http://people.csail.mit.edu/albert/bluez-intro/x559.html) in Linux.

For a Rust example that parallels that C code, look at [`ManagementSocket::open()`](https://github.com/laptou/bluez-rs/blob/01ee38b4c1b42359afedec1d6f8f1e3fa2e5ed02/src/socket.rs#L50-L95). This code is for opening an HCI management socket, which is used to access BlueZ's management API, but you can easily modify this code to open an L2CAP socket instead.

If you can, I would recommend getting your hands on _Bluetooth Essentials for Programmers_ by Huang and Rudolph. It's like the MIT CSAIL website I linked, but with a lot more detail.
